// =============================================================================
// BUILT-IN LABEL TEMPLATES
//
// Every template required by the brief, expressed purely as DATA. There is no
// per-template code anywhere in the engine — the same layout pipeline renders
// all of them, and the same pipeline will render templates a user designs in
// the future Custom Label Designer.
//
// Adding a template = appending one object to BUILTIN_TEMPLATES. No existing
// file changes, no renderer changes, no UI changes. That is the "future
// templates should be added without modifying existing code" requirement.
//
// These are seeded into label_templates as isSystem=true rows so they can be
// referenced by foreign key, cloned, and usage-counted — but they are defined
// here in code so a fresh install always has working defaults, and so a
// corrupted row can be re-seeded from a known-good source.
// =============================================================================

import { BarcodeSymbology, LabelTemplateKind } from "../../../../generated/prisma";
import type { LabelElement, LabelMargins } from "../label.types";

export interface BuiltinTemplate {
  code: string;
  name: string;
  description: string;
  kind: LabelTemplateKind;
  widthMm: number;
  heightMm: number;
  margins: LabelMargins;
  barcodeSymbology: BarcodeSymbology;
  rotation: number;
  elements: LabelElement[];
}

const TIGHT: LabelMargins = { top: 1, right: 1, bottom: 1, left: 1 };
const NARROW: LabelMargins = { top: 1.5, right: 2, bottom: 1.5, left: 2 };

/**
 * The standard 50×25mm clothing label: brand, product, size/colour, barcode and
 * price. This is the workhorse — it is the default for the Product module and
 * for purchase-receipt printing.
 */
const defaultClothing: BuiltinTemplate = {
  code: "default-clothing",
  name: "Default Clothing Label",
  description:
    "Standard 50×25mm garment label with brand, product, size/colour, barcode and price.",
  kind: LabelTemplateKind.PRODUCT,
  widthMm: 50,
  heightMm: 25,
  margins: TIGHT,
  barcodeSymbology: BarcodeSymbology.EAN13,
  rotation: 0,
  elements: [
    {
      id: "brand",
      type: "text",
      field: "brand",
      x: 0,
      y: 0,
      width: 48,
      fontSize: 7,
      bold: true,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 3.2,
      width: 48,
      fontSize: 6.5,
      align: "left",
      maxLines: 1,
    },
    {
      id: "variant",
      type: "text",
      field: "variantName",
      x: 0,
      y: 6.4,
      width: 30,
      fontSize: 6,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 30,
      y: 6.0,
      width: 18,
      fontSize: 9,
      bold: true,
      align: "right",
      showCurrency: true,
    },
    {
      id: "barcode",
      type: "barcode",
      field: "barcode",
      x: 2,
      y: 10,
      width: 44,
      height: 9,
      showBarcodeText: true,
      hideWhenEmpty: true,
    },
    {
      id: "sku",
      type: "text",
      field: "sku",
      x: 0,
      y: 21.5,
      width: 48,
      fontSize: 5,
      align: "center",
    },
  ],
};

/** Compact 38×19mm label for small garments and accessories. */
const smallLabel: BuiltinTemplate = {
  code: "small-label",
  name: "Small Label",
  description: "Compact 38×19mm label — barcode, price and SKU only.",
  kind: LabelTemplateKind.PRODUCT,
  widthMm: 38,
  heightMm: 19,
  margins: TIGHT,
  barcodeSymbology: BarcodeSymbology.EAN13,
  rotation: 0,
  elements: [
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 0,
      width: 36,
      fontSize: 5.5,
      bold: true,
      align: "center",
      maxLines: 1,
    },
    {
      id: "barcode",
      type: "barcode",
      field: "barcode",
      x: 1.5,
      y: 3.5,
      width: 33,
      height: 8,
      showBarcodeText: true,
      hideWhenEmpty: true,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 0,
      y: 13.5,
      width: 36,
      fontSize: 8,
      bold: true,
      align: "center",
      showCurrency: true,
    },
  ],
};

/** Roomy 75×50mm label with full attribution — used for premium/boxed stock. */
const largeLabel: BuiltinTemplate = {
  code: "large-label",
  name: "Large Label",
  description:
    "75×50mm label with store name, full product detail, barcode, MRP and selling price.",
  kind: LabelTemplateKind.PRODUCT,
  widthMm: 75,
  heightMm: 50,
  margins: NARROW,
  barcodeSymbology: BarcodeSymbology.EAN13,
  rotation: 0,
  elements: [
    {
      id: "store",
      type: "text",
      field: "storeName",
      x: 0,
      y: 0,
      width: 71,
      fontSize: 9,
      bold: true,
      align: "center",
    },
    { id: "rule1", type: "line", x: 0, y: 5, width: 71, thickness: 0.3 },
    {
      id: "brand",
      type: "text",
      field: "brand",
      x: 0,
      y: 6.5,
      width: 71,
      fontSize: 7.5,
      bold: true,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 11,
      width: 71,
      fontSize: 8,
      align: "left",
      maxLines: 2,
    },
    {
      id: "variant",
      type: "text",
      field: "variantName",
      x: 0,
      y: 19,
      width: 40,
      fontSize: 7,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "category",
      type: "text",
      field: "category",
      x: 0,
      y: 23,
      width: 40,
      fontSize: 6,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "mrp",
      type: "price",
      field: "mrp",
      x: 40,
      y: 18.5,
      width: 31,
      fontSize: 7,
      align: "right",
      showCurrency: true,
      strikeThrough: true,
      hideWhenEmpty: true,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 40,
      y: 22.5,
      width: 31,
      fontSize: 13,
      bold: true,
      align: "right",
      showCurrency: true,
    },
    {
      id: "barcode",
      type: "barcode",
      field: "barcode",
      x: 8,
      y: 30,
      width: 55,
      height: 12,
      showBarcodeText: true,
      hideWhenEmpty: true,
    },
    {
      id: "sku",
      type: "text",
      field: "sku",
      x: 0,
      y: 44.5,
      width: 71,
      fontSize: 6,
      align: "center",
    },
  ],
};

/** Barcode and nothing else — for re-tagging stock that already has price tags. */
const barcodeOnly: BuiltinTemplate = {
  code: "barcode-only",
  name: "Barcode Only",
  description: "40×20mm barcode with human-readable value. No pricing.",
  kind: LabelTemplateKind.BARCODE_ONLY,
  widthMm: 40,
  heightMm: 20,
  margins: TIGHT,
  barcodeSymbology: BarcodeSymbology.EAN13,
  rotation: 0,
  elements: [
    {
      id: "barcode",
      type: "barcode",
      field: "barcode",
      x: 1,
      y: 2,
      width: 36,
      height: 12,
      showBarcodeText: true,
    },
    {
      id: "sku",
      type: "text",
      field: "sku",
      x: 0,
      y: 16,
      width: 38,
      fontSize: 5.5,
      align: "center",
    },
  ],
};

/** Price-forward shelf-edge tag. Deliberately carries no barcode. */
const priceTag: BuiltinTemplate = {
  code: "price-tag",
  name: "Price Tag",
  description: "50×30mm price-forward tag with MRP and selling price. No barcode.",
  kind: LabelTemplateKind.PRICE_TAG,
  widthMm: 50,
  heightMm: 30,
  margins: NARROW,
  barcodeSymbology: BarcodeSymbology.NONE,
  rotation: 0,
  elements: [
    {
      id: "brand",
      type: "text",
      field: "brand",
      x: 0,
      y: 0,
      width: 46,
      fontSize: 7,
      bold: true,
      align: "center",
      hideWhenEmpty: true,
    },
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 4,
      width: 46,
      fontSize: 6.5,
      align: "center",
      maxLines: 2,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 0,
      y: 12,
      width: 46,
      fontSize: 18,
      bold: true,
      align: "center",
      showCurrency: true,
    },
    {
      id: "mrp",
      type: "price",
      field: "mrp",
      x: 0,
      y: 22.5,
      width: 46,
      fontSize: 7,
      align: "center",
      showCurrency: true,
      strikeThrough: true,
      hideWhenEmpty: true,
    },
  ],
};

/** Sale tag — leads with the discount, then the new price against a struck MRP. */
const saleTag: BuiltinTemplate = {
  code: "sale-tag",
  name: "Sale Tag",
  description: "50×30mm promotional tag leading with the discount percentage.",
  kind: LabelTemplateKind.SALE_TAG,
  widthMm: 50,
  heightMm: 30,
  margins: NARROW,
  barcodeSymbology: BarcodeSymbology.NONE,
  rotation: 0,
  elements: [
    { id: "banner", type: "box", x: 0, y: 0, width: 46, height: 7, filled: true },
    {
      id: "sale",
      type: "text",
      text: "SALE",
      x: 0,
      y: 1.2,
      width: 46,
      fontSize: 9,
      bold: true,
      align: "center",
    },
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 8.5,
      width: 46,
      fontSize: 6.5,
      align: "center",
      maxLines: 1,
    },
    {
      id: "discount",
      type: "text",
      field: "discountPercent",
      text: "%",
      x: 0,
      y: 12.5,
      width: 46,
      fontSize: 8,
      bold: true,
      align: "center",
      hideWhenEmpty: true,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 0,
      y: 17,
      width: 46,
      fontSize: 15,
      bold: true,
      align: "center",
      showCurrency: true,
    },
    {
      id: "mrp",
      type: "price",
      field: "mrp",
      x: 0,
      y: 25,
      width: 46,
      fontSize: 7,
      align: "center",
      showCurrency: true,
      strikeThrough: true,
      hideWhenEmpty: true,
    },
  ],
};

/** Clearance tag — final-sale styling, maximum price prominence. */
const clearanceTag: BuiltinTemplate = {
  code: "clearance-tag",
  name: "Clearance Tag",
  description: "50×30mm final-clearance tag with heavy border and struck MRP.",
  kind: LabelTemplateKind.CLEARANCE_TAG,
  widthMm: 50,
  heightMm: 30,
  margins: NARROW,
  barcodeSymbology: BarcodeSymbology.NONE,
  rotation: 0,
  elements: [
    { id: "border", type: "box", x: 0, y: 0, width: 46, height: 26, thickness: 0.6 },
    {
      id: "title",
      type: "text",
      text: "CLEARANCE",
      x: 0,
      y: 1.5,
      width: 46,
      fontSize: 8,
      bold: true,
      align: "center",
      letterSpacing: 0.4,
    },
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 1,
      y: 6.5,
      width: 44,
      fontSize: 6,
      align: "center",
      maxLines: 1,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 1,
      y: 11,
      width: 44,
      fontSize: 16,
      bold: true,
      align: "center",
      showCurrency: true,
    },
    {
      id: "mrp",
      type: "price",
      field: "mrp",
      x: 1,
      y: 20,
      width: 44,
      fontSize: 6.5,
      align: "center",
      showCurrency: true,
      strikeThrough: true,
      hideWhenEmpty: true,
    },
    {
      id: "sku",
      type: "text",
      field: "sku",
      x: 1,
      y: 23.5,
      width: 44,
      fontSize: 5,
      align: "center",
    },
  ],
};

/** Shelf-edge label: product identity, price and stock for floor staff. */
const shelfLabel: BuiltinTemplate = {
  code: "shelf-label",
  name: "Shelf Label",
  description: "60×30mm shelf-edge label with location, price, barcode and stock.",
  kind: LabelTemplateKind.SHELF_LABEL,
  widthMm: 60,
  heightMm: 30,
  margins: NARROW,
  barcodeSymbology: BarcodeSymbology.CODE128,
  rotation: 0,
  elements: [
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 0,
      width: 56,
      fontSize: 8,
      bold: true,
      align: "left",
      maxLines: 1,
    },
    {
      id: "variant",
      type: "text",
      field: "variantName",
      x: 0,
      y: 4.5,
      width: 34,
      fontSize: 6.5,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "location",
      type: "text",
      field: "shelfLocation",
      text: "Loc: ",
      x: 0,
      y: 8.5,
      width: 34,
      fontSize: 6,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "price",
      type: "price",
      field: "sellingPrice",
      x: 34,
      y: 4,
      width: 22,
      fontSize: 14,
      bold: true,
      align: "right",
      showCurrency: true,
    },
    {
      id: "barcode",
      type: "barcode",
      field: "barcode",
      x: 0,
      y: 13,
      width: 38,
      height: 10,
      showBarcodeText: true,
      hideWhenEmpty: true,
    },
    {
      id: "stock",
      type: "text",
      field: "currentStock",
      text: "Stock: ",
      x: 40,
      y: 18,
      width: 16,
      fontSize: 6,
      align: "right",
    },
    {
      id: "sku",
      type: "text",
      field: "sku",
      x: 0,
      y: 24.5,
      width: 56,
      fontSize: 5.5,
      align: "left",
    },
  ],
};

/** Warehouse label: bin/rack location first, large Code 128 for handheld guns. */
const warehouseLabel: BuiltinTemplate = {
  code: "warehouse-label",
  name: "Warehouse Label",
  description:
    "100×50mm warehouse label — storage location, large Code 128 barcode, batch and stock.",
  kind: LabelTemplateKind.WAREHOUSE_LABEL,
  widthMm: 100,
  heightMm: 50,
  margins: NARROW,
  barcodeSymbology: BarcodeSymbology.CODE128,
  rotation: 0,
  elements: [
    {
      id: "location",
      type: "text",
      field: "shelfLocation",
      x: 0,
      y: 0,
      width: 96,
      fontSize: 16,
      bold: true,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "warehouse",
      type: "text",
      field: "warehouse",
      x: 0,
      y: 8,
      width: 46,
      fontSize: 7,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "rack",
      type: "text",
      field: "rack",
      text: "Rack ",
      x: 46,
      y: 8,
      width: 25,
      fontSize: 7,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "bin",
      type: "text",
      field: "bin",
      text: "Bin ",
      x: 71,
      y: 8,
      width: 25,
      fontSize: 7,
      align: "left",
      hideWhenEmpty: true,
    },
    { id: "rule", type: "line", x: 0, y: 12.5, width: 96, thickness: 0.3 },
    {
      id: "product",
      type: "text",
      field: "productName",
      x: 0,
      y: 14,
      width: 96,
      fontSize: 8,
      bold: true,
      align: "left",
      maxLines: 1,
    },
    {
      id: "variant",
      type: "text",
      field: "variantName",
      x: 0,
      y: 18.5,
      width: 48,
      fontSize: 7,
      align: "left",
      hideWhenEmpty: true,
    },
    {
      id: "stock",
      type: "text",
      field: "currentStock",
      text: "Qty: ",
      x: 48,
      y: 18.5,
      width: 48,
      fontSize: 8,
      bold: true,
      align: "right",
    },
    {
      id: "barcode",
      type: "barcode",
      field: "barcode",
      x: 5,
      y: 23,
      width: 86,
      height: 16,
      showBarcodeText: true,
      hideWhenEmpty: true,
    },
    {
      id: "sku",
      type: "text",
      field: "sku",
      x: 0,
      y: 42,
      width: 48,
      fontSize: 6,
      align: "left",
    },
    {
      id: "batch",
      type: "text",
      field: "batchNumber",
      text: "Batch ",
      x: 48,
      y: 42,
      width: 48,
      fontSize: 6,
      align: "right",
      hideWhenEmpty: true,
    },
  ],
};

/**
 * The registry. Order here is the display order in the template picker.
 *
 * A new format is appended to this array and seeded — nothing else changes.
 */
export const BUILTIN_TEMPLATES: readonly BuiltinTemplate[] = [
  defaultClothing,
  smallLabel,
  largeLabel,
  barcodeOnly,
  priceTag,
  saleTag,
  clearanceTag,
  shelfLabel,
  warehouseLabel,
] as const;

/** The template used when a caller does not specify one and no default is set. */
export const FALLBACK_TEMPLATE_CODE = "default-clothing";

export function getBuiltinTemplate(code: string): BuiltinTemplate | undefined {
  return BUILTIN_TEMPLATES.find((template) => template.code === code);
}
